### Cadastrar administradores - POST


POST http://localhost:5162/api/administrador/cadastrar
Content-Type: application/json

{
  "Nome" : "Teste02",
  "Email" : "Teste0002@gmail.com",
  "Senha" : "SenhacomHash123"
}

### Listar Administradores GET

GET http://localhost:5162/api/administrador/listar
Content-Type: application/json
        
### Login validado com verificação da Hash - POST

POST http://localhost:5162/api/administrador/login
Content-Type: application/json

{
  
  "Email" : "Teste02@gmail.com",
  "Senha" : "Senhacoash123"
  
}

### atualizar dados através do ID

PUT http://localhost:5162/api/administrador/atualizar/2
Content-Type: application/json

{
    "nome": "TesteAtualizado",
    "email": "Testeatual@gmail.com",
    "senha": "Senhanova"
}

### deletar administrador - delete

DELETE http://localhost:5162/api/administrador/deletar/5

//*** testes participantes:

### Listar participantes - GET
GET http://localhost:5162/api/participante/listar
Content-Type: application/json

### Login participante - POST
POST http://localhost:5162/api/participante/login
Content-Type: application/json

{
  "Email": "participante01@gmail.com",
  "Senha": "SenhaComHash001"
}

### Atualizar participante - PUT
PUT http://localhost:5162/api/participante/atualizar/1
Content-Type: application/json

{
  "nome": "ParticipanteAtualizado",
  "email": "participanteAtual@gmail.com",
  "senha": "SenhaAtualizada001"
}

### Deletar participante - DELETE
DELETE http://localhost:5162/api/participante/deletar/1
